Point checkin of linux cross compiler for mingw. Don't try to build it yet.
git-svn-id: https://svn.alfresco.com/repos/alfresco-open-mirror/alfresco/HEAD@7364 7033f55c-6c29-4ad8-afba-765cb616e738

diff --git a/root/projects/clt/source/c/Makefile b/root/projects/clt/source/c/Makefile
--- a/root/projects/clt/source/c/Makefile
+++ b/root/projects/clt/source/c/Makefile
@@ -24,6 +24,7 @@
 # Author  Jon Cox  <jcox@alfresco.com>
 # File    Makefile
 # Use	  Compiles the Alfresco CLTs
+#	  Currently, this is just an examlar of how it will be done.
 #
 #------------------------------------------------------------------------------
 #
@@ -35,20 +36,127 @@
 #	(assuming your build environment is set up properly).
 #	
 #	The targeted  platform is specified by the command-line argument
-#	"PLATFORM=...", where the supported platforms are currently
-#	linux/i86 and win32/i86.   
+#	"TARGET_PLATFORM=...", where the supported platforms are currently
+#	linux/x86 and win32/x86.   
 #
 #	Thus the command:            make
-#	is equivalent to:            make PLATFORM=linux/i86
-#	but for a win32/i86, say:    make PLATFORM=win32/i86
+#	is equivalent to:            make TARGET_PLATFORM=linux/x86
+#	but for a win32/x86, say:    make TARGET_PLATFORM=win32/x86
 #
 #	The easiest way to set up a cross-compilation environment
 #	on Debian is to install the 'mingw32' package.
 #
+#       It might be worth investigating performance differences someday
+#       between different x86 versions.  An i686 CPU can run i586 and i386
+#       instructions but it may not execute as optimally as one specifically
+#       compiled for an i686.  The most common options are:
 #
-# SEE ALSO: 	
-#	http://www.fortran-2000.com/ArnaudRecipes/sharedlib.html
+#       x86_64 Processors
+#       -----------------
+#         o AMD's Athlon 64, Athlon 64-FX, and Opteron
+#         o Intel EMT64 - Nocona Xeon, Pentium 4's using revision EO
+#                         of the Prescott core (Pentium 4, model F)
+#         
+#       i686 Processors
+#       -----------------
+#         o All Intel 32-bit Pentiums (excluding Pentium 1 and Pentium MMX)
+#         o All AMD 32-bit Athlons
+#         
+#       i586 Processors
+#       -----------------
+#         o All 32-bit AMD Ks
+#         o Pentium 1
+#         o Pentium MMX
+#         
+#       i386 Processors
+#       -----------------
+#         o Lowest common denominator for Intel 80386 compatible CPUs.
+#           This includes all of the above, but does not take advantage 
+#           of various extended instructions.
+#
+# 	See also:  http://www.fortran-2000.com/ArnaudRecipes/sharedlib.html
+#
 #------------------------------------------------------------------------------
+#
+#    Official gcc naming scheme for cross compilation 
+#    ------------------------------------------------
+#
+#	The gcc cross tool chain has adopted the following scheme to
+#	identify a host/build/target platform:
+#
+#		<cpu>-<manufacturer>-<kernel>-<os>
+#
+#	For example:
+#	
+#		i686-pc-linux-gnu 
+#
+#	This is the instruction set of an i686, and is an IBM compatible PC
+#	running the linux kernel on the GNU os.  The command "uname -smo" says:
+#
+#		Linux i686 GNU/Linux
+#
+#
+#
+#    Cross compilation data: (from gccinstall.info)
+#    ----------------------------------------------
+#
+#	Here are the possible CPU types:
+#
+#	     1750a, a29k, alpha, arm, avr, cN, clipper, dsp16xx, elxsi, fr30,
+#	     h8300, hppa1.0, hppa1.1, i370, i386, i486, i586, i686, i786, i860,
+#	     i960, ip2k, m32r, m68000, m68k, m6811, m6812, m88k, mcore, mips,
+#	     mipsel, mips64, mips64el, mn10200, mn10300, ns32k, pdp11, powerpc,
+#	     powerpcle, romp, rs6000, sh, sparc, sparclite, sparc64, v850, vax,
+#	     we32k.
+#
+#	Here are the recognized company names.  As you can see, customary
+#	abbreviations are used rather than the longer official names.
+#
+#	     acorn, alliant, altos, apollo, apple, att, bull, cbm, convergent,
+#	     convex, crds, dec, dg, dolphin, elxsi, encore, harris, hitachi,
+#	     hp, ibm, intergraph, isi, mips, motorola, ncr, next, ns, omron,
+#	     plexus, sequent, sgi, sony, sun, tti, unicom, wrs.
+#
+#	The company name is meaningful only to disambiguate when the rest of
+#	the information supplied is insufficient.  You can omit it, writing
+#	just `CPU-SYSTEM', if it is not needed.  For example, `vax-ultrix4.2'
+#	is equivalent to `vax-dec-ultrix4.2'.
+#
+#	Here is a list of system types:
+#
+#	    386bsd, aix, acis, amigaos, aos, aout, aux, bosx, bsd, clix, coff,
+#	    ctix, cxux, dgux, dynix, ebmon, ecoff, elf, esix, freebsd, hms,
+#	    genix, gnu, linux, linux-gnu, hiux, hpux, iris, irix, isc, luna,
+#	    lynxos, mach, minix, msdos, mvs, netbsd, newsos, nindy, ns, osf,
+#	    osfrose, ptx, riscix, riscos, rtu, sco, sim, solaris, sunos, sym,
+#	    sysv, udi, ultrix, unicos, uniplus, unos, vms, vsta, vxworks,
+#	    winnt, xenix.
+#
+#    Chip Arch.       "Common chip names"
+#   ----------------+---------------------------------------------------------
+#     8086 = 8-bit  |
+#   ----------------+---------------------------------------------------------
+#    80186 = 8-bit  |
+#   ----------------+---------------------------------------------------------
+#    80286 = 16-bit |
+#   ----------------+---------------------------------------------------------
+#    80386 = 32-bit |
+#   ----------------+---------------------------------------------------------
+#    80486 = 32-bit |
+#   ----------------+---------------------------------------------------------
+#    80586 = 32-bit | Pentium, Pentium MMX, K5, K6, K6-II, K6-III
+#   ----------------+---------------------------------------------------------
+#    80686 = 32-bit | Pentium Pro, Pentium II, Pentium III, Athlon, Athlon XP, 
+#                   | Opteron*, Athlon FX-51*, Athlon FX-53*, Athlon 64*
+#                   |
+#                   | *= 32-bit/64-bit
+#   ----------------+---------------------------------------------------------
+#    80786 = 32-bit | Pentium 4
+#   ----------------+---------------------------------------------------------
+#
+#
+#------------------------------------------------------------------------------
+
 
 all	: clt
 .PHONY	: all clt check-platform mkdirs clean clean-platform
@@ -59,36 +167,48 @@ BUILD_DIR_BASE		= $(TOP)/../../build/obj
 DIST_DIR_BASE		= $(TOP)/../../build/dist
 INCLUDE			= $(SOURCE_DIR)
 INCLUDES 		= -I $(INCLUDE)
-
+LDFLAGS			= -L$(DIST_DIR)
+SH_LDFLAGS		= -shared
+OBJ_EXT			= .o
+BUILD_DIR		= $(BUILD_DIR_BASE)/$(TARGET_PLATFORM)
+DIST_DIR		= $(DIST_DIR_BASE)/$(TARGET_PLATFORM)
 
 #-----------------------------------------------------------------------------
 # Misc intermediate variables
 #-----------------------------------------------------------------------------
 
-PLATFORM=linux/i86
+TARGET_PLATFORM=linux/x86
 
-ifeq ($(PLATFORM),linux/i86)
-	BUILD_DIR	= $(BUILD_DIR_BASE)/$(PLATFORM)
-	DIST_DIR	= $(DIST_DIR_BASE)/$(PLATFORM)
+
+ifeq ($(TARGET_PLATFORM),linux/x86)
 	CC		= gcc
 	CFLAGS		= -fPIC -Wall
-	LINK_FLAGS	= -shared -L$(DIST_DIR)
+	LIBS		=
 	SHARED_LIB_EXT	= .so
-	OBJ_EXT		= .o
 	EXE_EXT		=
-else ifeq ($(PLATFORM),win32/i86)
-	BUILD_DIR	= $(BUILD_DIR_BASE)/$(PLATFORM)
-	DIST_DIR	= $(DIST_DIR_BASE)/$(PLATFORM)
-	CC		= i586-mingw32msvc-cc
+	#
+	# TODO:  Create controlled build environment on Linux 
+	#	 rather than rely on whatever is present.
+	#
+else ifeq ($(TARGET_PLATFORM),win32/x86)
+	CC		= i386-mingw32-gcc  
 	CFLAGS		= -Wall
-	LINK_FLAGS	= -shared -L$(DIST_DIR)
+	LIBS		= -lws2_32
 	SHARED_LIB_EXT	= .dll
-	OBJ_EXT		= .o
 	EXE_EXT		= .exe
+
+	# Set the compiler prefix on a linux machine
+	compiler_prefix = $(subst Linux-i386,$(MINGW_ROOT)/usr,$(BUILD_PLATFORM))
+
+	# Massage variables & PATH to deal with compilers on each build platform
+	PATH	:=   $(compiler_prefix)/bin:$(PATH)
+	CFLAGS	+= -I$(compiler_prefix)/include
+	LDFLAGS	+= -B$(compiler_prefix)/lib
 else
-	CC		= echo "ERROR!  unsupported platform: $(PLATFORM)"
+	CC		= echo "ERROR!  unsupported platform: $(TARGET_PLATFORM)"
 	UNSUPPORTED	= true
 endif
+
 
 
 #-----------------------------------------------------------------------------
@@ -97,11 +217,12 @@ endif
 CLT_PROGRAM_SOURCES	= 
 CLT_LIBRARY_SOURCES	=
 CLT_LIBRARY		=
-#
+
 # CLT_PROGRAM_SOURCES	= driver_1.c driver_2.c
 # CLT_LIBRARY_SOURCES	= xxx.c yyy.c
-# CLT_LIBRARY		= libalfresco-clt
-#
+# CLT_LIBRARY_STEM	= alfresco-clt
+# CLT_LIBRARY		= lib$(CLT_LIBRARY_STEM)
+
 
 
 #=============================================================================
@@ -139,18 +260,20 @@ clt:   check-platform mkdirs $(CLT_PROGS)
 # Remove all build artifacts from current build platform
 #-----------------------------------------------------------------------------
 check-platform:
-	@if [ -n "$(UNSUPPORTED)" ] ; then  				    \
-	    echo "ERROR:  Unsupported Alfresco CLT platform '$(PLATFORM)'"; \
-	    exit 1;							    \
+	@if [ -n "$(UNSUPPORTED)" ] ; then  				     \
+	    echo "ERROR:  Unsupported target platform '$(TARGET_PLATFORM)'"; \
+	    exit 1;							     \
 	fi
 
 clean:	check-platform
+	echo path is $(PATH)
 	rm -rf  $(BUILD_DIR_BASE)/*
 	rm -rf  $(DIST_DIR_BASE)/*
 
+
 clean-platform:  check-platform
-	rm -rf  $(BUILD_DIR_BASE)/$(PLATFORM)/*
-	rm -rf  $(DIST_DIR_BASE)/$(PLATFORM)/*
+	rm -rf  $(BUILD_DIR_BASE)/$(TARGET_PLATFORM)/*
+	rm -rf  $(DIST_DIR_BASE)/$(TARGET_PLATFORM)/*
 
 
 #-----------------------------------------------------------------------------
@@ -175,7 +298,7 @@ $(DIST_DIR):
 # Create the shared library
 #-----------------------------------------------------------------------------
 $(CLT_LIB): $(CLT_LIB_OBJ)
-	$(CC) $(LINK_FLAGS) -o  $@  $(CFLAGS) $(CLT_LIB_OBJ)
+	$(CC) $(SH_LDFLAGS) $(LDFLAGS) -o  $@  $(CFLAGS) $(CLT_LIB_OBJ)
 
 
 #-----------------------------------------------------------------------------
@@ -194,5 +317,6 @@ $(BUILD_DIR)/%$(OBJ_EXT):
 #-----------------------------------------------------------------------------
 .SECONDEXPANSION:
 $(CLT_PROGS): $(BUILD_DIR)/$$(basename $$(notdir $$@))$(OBJ_EXT)  $(CLT_LIB)
-	$(CC) -o $@ $(BUILD_DIR)/$(basename $(notdir $@))$(OBJ_EXT) $(CLT_LIB)
+	$(CC) -o $@ $(BUILD_DIR)/$(basename $(notdir $@))$(OBJ_EXT) \
+            $(LDFLAGS) -l$(CLT_LIBRARY_STEM)  $(LIBS)
 
